name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:     
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      run: |
        docker info > /dev/null 2>&1
        
        # Ensure that Docker is running...
        if [ $? -ne 0 ]; then
            echo "Docker is not running."
        
            exit 1
        fi
        
        docker run --rm \
            -v $(pwd):/opt \
            -w /opt \
            laravelsail/php80-composer:latest \
            bash -c "laravel restaurant-app && cd restaurant-app && php ./artisan sail:install --with=mysql,redis,meilisearch,mailhog,selenium"
            
        cd restaurant-app
    - uses: actions/checkout@v2
    - name: Launch docker environment
      run: vendor/bin/sail up
    - name: Execute tests
      run: vendor/bin/sail test
