name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:     
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Launch docker environment
      run: vendor/bin/sail up
    - name: Execute tests
      run: vendor/bin/sail test
